drop table user if exists;
drop table role if exists;
create table user(
	id bigint generated by default as identity,
	username varchar(40), 
	name varchar(20), 
	age int(3), 
	balance decimal(10,2), 
	roleid bigint,
	primary key(id)
);

create table role(
	id bigint generated by default as identity,
	rolename varchar(40), 
	description varchar(200), 
	primary key(id)
);