#安全认证密码
security:
  user:
    name: user1
    password: password1
  basic:
    enabled: true

server:
  port: 8761 #默认端口就是8761
  
#单点eureka配置如下
eureka:
  client:
    health-check:
      enabled: true #开启健康检查
    register-with-eureka: false #不向其他eureka服务节点注册
    fetch-registry: false #不向其他eureka服务注册
    service-url:  
      defaultZone: http://user1:password1@localhost:8761/eureka