eureka:
  client:
    service-url:
      defaultZone: http://user1:password1@eureka-ha-1:8761/eureka,http://user1:password1@eureka-ha-2:8761/eureka #这个地方比较恶心啊，居然要写一堆
  instance:
    prefer-ip-address: true #默认是false
    #instance-id，可以自己配置显示名称
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#这个比较重要哦，默认是false, 不对feign客户端进行Hystrix监控，老版本也没这个问题
feign.hystrix.enabled: true 
#/health界面的其他属性，默认是true不显示，奇葩了，老版本这些都没问题，新版本默认值都变了
management.security.enabled: false

spring:
  application:
    name: microservice-consumer-order-config
server:
  port: 8500
